// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VControleDeVistoria.Infra.Data.Context;

#nullable disable

namespace ControleDeVistoria.Infra.Data.Migrations.Vistoria
{
    [DbContext(typeof(VistoriaContext))]
    partial class VistoriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Ambiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObsEletrica")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ObsEsquadrias")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ObsHidraulica")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ObsPintura")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ObsPiso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ObsTeto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("ReparoEletrica")
                        .HasColumnType("bit");

                    b.Property<bool>("ReparoEsquadrias")
                        .HasColumnType("bit");

                    b.Property<bool>("ReparoHidraulica")
                        .HasColumnType("bit");

                    b.Property<bool>("ReparoPintura")
                        .HasColumnType("bit");

                    b.Property<bool>("ReparoPiso")
                        .HasColumnType("bit");

                    b.Property<bool>("ReparoTeto")
                        .HasColumnType("bit");

                    b.Property<string>("SituacaoEletrica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituacaoEsquadrias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituacaoHidraulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituacaoPintura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituacaoPiso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituacaoTeto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VistoriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VistoriaId");

                    b.ToTable("Ambientes");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ImovelId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoImovel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Locatario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImovelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId")
                        .IsUnique();

                    b.ToTable("Locatarios");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Vistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVistoria")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImovelId")
                        .HasColumnType("int");

                    b.Property<int>("MedidorAgua")
                        .HasColumnType("int");

                    b.Property<int>("MedidorEnergia")
                        .HasColumnType("int");

                    b.Property<int>("TipoVistoria")
                        .HasColumnType("int");

                    b.Property<int>("VistoriadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId")
                        .IsUnique();

                    b.HasIndex("VistoriadorId");

                    b.ToTable("Vistorias");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Vistoriador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vistoriadores");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Ambiente", b =>
                {
                    b.HasOne("ControleDeVistoria.Domain.Entities.Vistoria", "Vistoria")
                        .WithMany("Ambiente")
                        .HasForeignKey("VistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vistoria");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("ControleDeVistoria.Domain.Entities.Imovel", "Imovel")
                        .WithOne("Endereco")
                        .HasForeignKey("ControleDeVistoria.Domain.Entities.Endereco", "ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Locatario", b =>
                {
                    b.HasOne("ControleDeVistoria.Domain.Entities.Imovel", "Imovel")
                        .WithOne("Locatario")
                        .HasForeignKey("ControleDeVistoria.Domain.Entities.Locatario", "ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Vistoria", b =>
                {
                    b.HasOne("ControleDeVistoria.Domain.Entities.Imovel", "Imovel")
                        .WithOne("Vistoria")
                        .HasForeignKey("ControleDeVistoria.Domain.Entities.Vistoria", "ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleDeVistoria.Domain.Entities.Vistoriador", "Vistoriador")
                        .WithMany("Vistoria")
                        .HasForeignKey("VistoriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");

                    b.Navigation("Vistoriador");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Imovel", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Locatario");

                    b.Navigation("Vistoria");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Vistoria", b =>
                {
                    b.Navigation("Ambiente");
                });

            modelBuilder.Entity("ControleDeVistoria.Domain.Entities.Vistoriador", b =>
                {
                    b.Navigation("Vistoria");
                });
#pragma warning restore 612, 618
        }
    }
}
